"""
Django settings for oasis project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from oscar.defaults import *
import os
import environ

env = environ.Env()

# Path helper
location = lambda x: os.path.join(
    os.path.dirname(os.path.realpath(__file__)), x)

#DEBUG = env.bool('DEBUG', default=True)

#ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1', '10.132.45.42'])
#ALLOWED_HOSTS = ["10.132.45.42", "127.0.0.1", "localhost"]
ALLOWED_HOSTS = ['*']

EMAIL_SUBJECT_PREFIX = '[Oscar sandbox]'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-twekob**1cvid#27o=9gf%*+()i)0na*cag_=t0@ubo#@yh+6-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'restaurant.apps.RestaurantConfig',
    'rest_framework',
    "rest_framework.authtoken",
    'corsheaders',

    'oscar.config.Shop',
    'oscar.apps.analytics.apps.AnalyticsConfig',
    #'oscar.apps.checkout.apps.CheckoutConfig',
    'apps.checkout.apps.CheckoutConfig',
    #'oscar.apps.address.apps.AddressConfig',
    'apps.address.apps.AddressConfig',
    #'oscar.apps.shipping.apps.ShippingConfig',
    'apps.shipping.apps.ShippingConfig',
    #'oscar.apps.catalogue.apps.CatalogueConfig',
    'apps.catalogue.apps.CatalogueConfig',
    'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
    'oscar.apps.communication.apps.CommunicationConfig',
    'oscar.apps.partner.apps.PartnerConfig',
    #'apps.partner.apps.PartnerConfig',
    'oscar.apps.basket.apps.BasketConfig',
    #'oscar.apps.payment.apps.PaymentConfig',
    'apps.payment.apps.PaymentConfig',
    'oscar.apps.offer.apps.OfferConfig',
    'apps.order.apps.OrderConfig',
    #'oscar.apps.order.apps.OrderConfig',
    'oscar.apps.customer.apps.CustomerConfig',
    #'oscar.apps.search.apps.SearchConfig',
    'apps.search.apps.SearchConfig',
    'oscar.apps.voucher.apps.VoucherConfig',
    'oscar.apps.wishlists.apps.WishlistsConfig',
    'oscar.apps.dashboard.apps.DashboardConfig',
    'oscar.apps.dashboard.reports.apps.ReportsDashboardConfig',
    'oscar.apps.dashboard.users.apps.UsersDashboardConfig',
    'oscar.apps.dashboard.orders.apps.OrdersDashboardConfig',
    'oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig',
    'oscar.apps.dashboard.offers.apps.OffersDashboardConfig',
    'oscar.apps.dashboard.partners.apps.PartnersDashboardConfig',
    'oscar.apps.dashboard.pages.apps.PagesDashboardConfig',
    'oscar.apps.dashboard.ranges.apps.RangesDashboardConfig',
    'oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig',
    'oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig',
    'oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig',
    'oscar.apps.dashboard.shipping.apps.ShippingDashboardConfig',

    # 3rd-party apps that oscar depends on
    'haystack',
    'treebeard',
    'sorl.thumbnail',   # Default thumbnail backend, can be replaced
    'django_tables2',
    #'theme', 
    'tailwind',
    #'django_browser_reload',
    
    # Third party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'widget_tweaks',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

TAILWIND_APP_NAME = 'theme'

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'corsheaders.middleware.CorsMiddleware',

    'oscar.apps.basket.middleware.BasketMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'oasis.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            location('templates'),
        ],
        'OPTIONS': {
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.contrib.messages.context_processors.messages',

                # Oscar specific
                'oscar.apps.search.context_processors.search_form',
                'oscar.apps.communication.notifications.context_processors.notifications',
                'oscar.apps.checkout.context_processors.checkout',
                'oscar.core.context_processors.metadata',

                # Custom context processor
                'oasis.context_processors.modern_settings',
            ],
            'debug': DEBUG,
        }
    }
]
WSGI_APPLICATION = 'oasis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
        'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    'oscar.apps.customer.auth_backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

'''
# Allauth settings
LOGIN_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_REQUIRED = True
'''

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        'APP': {
            'client_id': '789007336886-efm2802u73l1fjfk347f5m11ldbrcuij.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        }
    }
}

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
    },
}

location = lambda x: os.path.join(
    os.path.dirname(os.path.realpath(__file__)), x)


MEDIA_ROOT = location("public/media")

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash if there is a path component (optional in other cases).
# Examples: "http://media.lawrence.com", "http://example.com/media/"
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
STATIC_ROOT = location('public/static')
STATICFILES_DIRS = (
    location('static/'),
)
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'en-gb'

# Includes all languages that have >50% coverage in Transifex
# Taken from Django's default setting for LANGUAGES
gettext_noop = lambda s: s
LANGUAGES = (
    ('en-gb', gettext_noop('British English')),
    ('ar', gettext_noop('Arabic')),
    ('ca', gettext_noop('Catalan')),
    ('cs', gettext_noop('Czech')),
    ('da', gettext_noop('Danish')),
    ('de', gettext_noop('German')),
    ('el', gettext_noop('Greek')),
    ('es', gettext_noop('Spanish')),
    ('fi', gettext_noop('Finnish')),
    ('fr', gettext_noop('French')),
    ('it', gettext_noop('Italian')),
    ('ko', gettext_noop('Korean')),
    ('nl', gettext_noop('Dutch')),
    ('pl', gettext_noop('Polish')),
    ('pt', gettext_noop('Portuguese')),
    ('pt-br', gettext_noop('Brazilian Portuguese')),
    ('ro', gettext_noop('Romanian')),
    ('ru', gettext_noop('Russian')),
    ('sk', gettext_noop('Slovak')),
    ('uk', gettext_noop('Ukrainian')),
    ('zh-cn', gettext_noop('Simplified Chinese')),
)


CACHES = {
    'default': env.cache(default='locmemcache://'),
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OSCAR_SHOP_NAME = "Oasis"
OSCAR_SHOP_TAGLINE = "Premium with less cost"

OSCAR_RECENTLY_VIEWED_PRODUCTS = 5
OSCAR_ALLOW_ANON_CHECKOUT = True

# Oscar's default currency
OSCAR_DEFAULT_CURRENCY = 'GHS' # Or your preferred currency

# Oscar's default image folder
OSCAR_IMAGE_FOLDER = 'images/products'

# Oscar's default product image size
OSCAR_THUMBNAIL_SIZES = {
    'dashboard': '100x100',
    'catalogue': '150x150',
    'product_page': '300x300',
    'checkout': '80x80',
}

# Oscar's default product image quality
OSCAR_THUMBNAIL_QUALITY = 90

# Oscar's default product image format
OSCAR_THUMBNAIL_FORMAT = 'PNG'

# Oscar's default product image background
OSCAR_THUMBNAIL_BG_COLOUR = '#FFFFFF'

# Oscar's default product image crop
OSCAR_THUMBNAIL_CROP = 'center'

# Oscar's default product image upscale
OSCAR_THUMBNAIL_UPSCALE = True

# Oscar's default product image fill
OSCAR_THUMBNAIL_FILL = True

# Oscar's default product image padding
OSCAR_THUMBNAIL_PADDING = True

# Oscar's default product image padding colour
OSCAR_THUMBNAIL_PADDING_COLOUR = '#FFFFFF'

# Oscar's default product image padding border
OSCAR_THUMBNAIL_PADDING_BORDER = True

# Oscar's default product image padding border colour
OSCAR_THUMBNAIL_PADDING_BORDER_COLOUR = '#000000'

# Oscar's default product image padding border width
OSCAR_THUMBNAIL_PADDING_BORDER_WIDTH = 1

# Oscar's default product image padding border radius
OSCAR_THUMBNAIL_PADDING_BORDER_RADIUS = 0

# Oscar's default product image padding border style
OSCAR_THUMBNAIL_PADDING_BORDER_STYLE = 'solid'

# Oscar's default product image padding border opacity
OSCAR_THUMBNAIL_PADDING_BORDER_OPACITY = 1

# Oscar's default product image padding border shadow
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW = False

# Oscar's default product image padding border shadow colour
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_COLOUR = '#000000'

# Oscar's default product image padding border shadow x
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_X = 0

# Oscar's default product image padding border shadow y
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_Y = 0

# Oscar's default product image padding border shadow blur
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_BLUR = 0

# Oscar's default product image padding border shadow spread
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_SPREAD = 0

# Oscar's default product image padding border shadow inset
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_INSET = False

# Oscar's default product image padding border shadow opacity
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_OPACITY = 1

# Oscar's default product image padding border shadow rgba
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_RGBA = (0, 0, 0, 1)

# Oscar's default product image padding border shadow rgb
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_RGB = (0, 0, 0)

# Oscar's default product image padding border shadow hex
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_HEX = '#000000'

# Oscar's default product image padding border shadow hsv
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_HSV = (0, 0, 0)

# Oscar's default product image padding border shadow hsl
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_HSL = (0, 0, 0)

# Oscar's default product image padding border shadow cmyk
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_CMYK = (0, 0, 0, 0)

# Oscar's default product image padding border shadow gray
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_GRAY = 0

# Oscar's default product image padding border shadow alpha
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_ALPHA = 1

# Oscar's default product image padding border shadow css
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_CSS = '0 0 0 0 rgba(0,0,0,1)'

# Oscar's default product image padding border shadow css inset
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_CSS_INSET = 'inset 0 0 0 0 rgba(0,0,0,1)'

# Oscar's default product image padding border shadow css outset
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_CSS_OUTSET = '0 0 0 0 rgba(0,0,0,1)'


# Paystack settings
#PAYSTACK_SECRET_KEY = "sk_live_cce8b8031db9486fa923cf3701bc4540893f9a3e"
#PAYSTACK_PUBLIC_KEY = "pk_live_1ee2a9c93d1f34b41a965b1c22c1a4d4e5415ce7"
