# Generated by Django 5.2.4 on 2025-07-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='hostel',
            field=models.CharField(default='Indece', max_length=128, verbose_name='Hall/Hostel'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='location',
            field=models.CharField(choices=[('campus', 'Campus'), ('tech_junction', 'Tech Junction'), ('ayeduase', 'Ayeduase'), ('kotei', 'Kotei'), ('deduako', 'Deduako'), ('new_site', 'New Site')], default='campus', max_length=128, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='room_number',
            field=models.CharField(default='001', max_length=10, verbose_name='Room number'),
        ),
    ]
