# Generated by Django 5.2.4 on 2025-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_useraddress_hostel_useraddress_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='hostel',
            field=models.CharField(default='Indece', max_length=128, verbose_name='Hostel/Hall'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='location',
            field=models.CharField(choices=[('campus', 'Campus'), ('tech_junction', 'Tech Junction'), ('ayeduase', 'Ayeduase'), ('kotei', 'Kotei'), ('atonsu', 'Atonsu'), ('deduako', 'Deduako'), ('new_site', 'New Site')], default='campus', max_length=128, verbose_name='Location'),
        ),
    ]
