# Generated by Django 5.2.4 on 2025-08-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_useraddress_hostel_alter_useraddress_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='Ghana', verbose_name='country'),
        ),
    ]
