# Generated by Django 5.2.4 on 2025-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_alter_useraddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(default='0123456789', verbose_name='Phone Number'),
        ),
    ]
