# Generated by Django 5.2.4 on 2025-08-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_useraddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='Ghana', verbose_name='Country'),
        ),
    ]
