# Generated by Django 5.2.4 on 2025-08-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_alter_useraddress_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(default='0123456789', max_length=10, verbose_name='Phone Number'),
        ),
    ]
