# Generated by Django 5.2.4 on 2025-08-08 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_alter_useraddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(default='0123456789', help_text='Enter a valid 10-digit phone number starting with 0', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 0.', regex='^0\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
