# Generated by Django 5.2.4 on 2025-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200801_0817'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.PositiveIntegerField()),
                ('ref', models.CharField(max_length=100, unique=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
