# Generated by Django 5.2.4 on 2025-07-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_paystackpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaystackPayment',
        ),
        migrations.AddField(
            model_name='source',
            name='paystack_reference',
            field=models.CharField(default='3240', max_length=100, unique=True),
        ),
    ]
