# Generated by Django 5.2.4 on 2025-07-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_source_paystack_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='paystack_reference',
            field=models.CharField(default='1547', max_length=100),
        ),
    ]
