"""
Django settings for oasis project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from oscar.defaults import *
import environ

env = environ.Env()
#import environ

#env = os.environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qkg(%1%ssy(i836o3r5bwus^ipx*r%31evsa$nnrk5xij4nq4k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django.contrib.flatpages',


    'oscar.config.Shop',
    'oscar.apps.analytics.apps.AnalyticsConfig',
    'oscar.apps.checkout.apps.CheckoutConfig',
    'oscar.apps.address.apps.AddressConfig',
    'oscar.apps.shipping.apps.ShippingConfig',
    'oscar.apps.catalogue.apps.CatalogueConfig',
    'oscar.apps.catalogue.reviews.apps.CatalogueReviewsConfig',
    'oscar.apps.communication.apps.CommunicationConfig',
    'oscar.apps.partner.apps.PartnerConfig',
    'oscar.apps.basket.apps.BasketConfig',
    'oscar.apps.payment.apps.PaymentConfig',
    'oscar.apps.offer.apps.OfferConfig',
    'oscar.apps.order.apps.OrderConfig',
    'oscar.apps.customer.apps.CustomerConfig',
    #'oscar.apps.search.apps.SearchConfig',
    'oasis.search.apps.SearchConfig',
    'oscar.apps.voucher.apps.VoucherConfig',
    'oscar.apps.wishlists.apps.WishlistsConfig',
    'oscar.apps.dashboard.apps.DashboardConfig',
    'oscar.apps.dashboard.reports.apps.ReportsDashboardConfig',
    'oscar.apps.dashboard.users.apps.UsersDashboardConfig',
    'oscar.apps.dashboard.orders.apps.OrdersDashboardConfig',
    'oscar.apps.dashboard.catalogue.apps.CatalogueDashboardConfig',
    'oscar.apps.dashboard.offers.apps.OffersDashboardConfig',
    'oscar.apps.dashboard.partners.apps.PartnersDashboardConfig',
    'oscar.apps.dashboard.pages.apps.PagesDashboardConfig',
    'oscar.apps.dashboard.ranges.apps.RangesDashboardConfig',
    'oscar.apps.dashboard.reviews.apps.ReviewsDashboardConfig',
    'oscar.apps.dashboard.vouchers.apps.VouchersDashboardConfig',
    'oscar.apps.dashboard.communications.apps.CommunicationsDashboardConfig',
    'oscar.apps.dashboard.shipping.apps.ShippingDashboardConfig',

    # 3rd-party apps that Oscar depends on
    'widget_tweaks',
    'haystack',
    'treebeard',
    'sorl.thumbnail',
    'easy_thumbnails',
    'django_tables2',

    # Django apps that the sandbox depends on
    'django.contrib.sitemaps',
]

SITE_ID = 1


# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale
USE_L10N = True


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',

    # Allow languages to be selected
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
    'django.middleware.common.CommonMiddleware',

    # Ensure a valid basket is added to the request instance for every request
    'oscar.apps.basket.middleware.BasketMiddleware',
]

ROOT_URLCONF = 'oasis.urls'

# A sample logging configuration. The only tangible logging
# performed by this configuration is to send an email to
# the site admins on every HTTP 500 error.
# See http://docs.djangoproject.com/en/dev/topics/logging for
# more details on how to customize your logging configuration.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s',
        },
        'simple': {
            'format': '[%(asctime)s] %(message)s'
        },
    },
    'root': {
        'level': 'DEBUG',
        'handlers': ['console'],
    },
    'handlers': {
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'oscar': {
            'level': 'DEBUG',
            'propagate': True,
        },
        'oscar.catalogue.import': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'oscar.alerts': {
            'handlers': ['null'],
            'level': 'INFO',
            'propagate': False,
        },

        # Django loggers
        'django': {
            'handlers': ['null'],
            'propagate': True,
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.db.backends': {
            'level': 'WARNING',
            'propagate': True,
        },
        'django.security.DisallowedHost': {
            'handlers': ['null'],
            'propagate': False,
        },

        # Third party
        'raven': {
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
        'sorl.thumbnail': {
            'handlers': ['console'],
            'propagate': True,
            'level': 'INFO',
        },
    }
}


AUTHENTICATION_BACKENDS = (
    'oscar.apps.customer.auth_backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
)


CACHES = {
    'default': env.cache(default='locmemcache://'),
}

# Path helper
location = lambda x: os.path.join(os.path.dirname(os.path.realpath(__file__)), x)

#DEBUG = env.bool('DEBUG', default=True)

HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

HAYSTACK_CONNECTIONS = {
 'default': {
 'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
 },
 }

'''
# Woosh settings

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': location('whoosh_index'),
        'INCLUDE_SPELLING': True,
    },
}'''
'''

HAYSTACK_CONNECTIONS = {
   'default': {
         'ENGINE': 'haystack.backends.solr_backend.SolrEngine',
         'URL': 'http://127.0.0.1:8983/solr/sandbox',
        'ADMIN_URL': 'http://127.0.0.1:8983/solr/admin/cores',
        'INCLUDE_SPELLING': True,
    }
}'''

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            location('templates'),
        ],
        'OPTIONS': {
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.contrib.messages.context_processors.messages',

                # Oscar specific
                'oscar.apps.search.context_processors.search_form',
                'oscar.apps.communication.notifications.context_processors.notifications',
                'oscar.apps.checkout.context_processors.checkout',
                'oscar.core.context_processors.metadata',
            ],
            'debug': DEBUG,
        }
    }
]


WSGI_APPLICATION = 'oasis.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
        'ATOMIC_REQUESTS': True,
    }
}

OSCAR_INITIAL_ORDER_STATUS = 'Pending'
OSCAR_INITIAL_LINE_STATUS = 'Pending'
OSCAR_ORDER_STATUS_PIPELINE = {
    'Pending': ('Being processed', 'Cancelled',),
    'Being processed': ('Processed', 'Cancelled',),
    'Cancelled': (),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Absolute path to the directory that holds media.
# Example: "/home/media/media.lawrence.com/"
MEDIA_ROOT = location("public/media")

# URL that handles the media served from MEDIA_ROOT. Make sure to use a
# trailing slash if there is a path component (optional in other cases).
# Examples: "http://media.lawrence.com", "http://example.com/media/"
MEDIA_URL = '/media/'

STATIC_URL = '/static/'
STATIC_ROOT = location('public/static')
STATICFILES_DIRS = (
    location('static/'),
)
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

OSCAR_SHOP_NAME = "Oasis"
OSCAR_SHOP_TAGLINE = "Premium with less cost"

OSCAR_RECENTLY_VIEWED_PRODUCTS = 20
OSCAR_ALLOW_ANON_CHECKOUT = True

# Oscar's default currency
OSCAR_DEFAULT_CURRENCY = 'GHS' # Or your preferred currency

# Oscar's default image folder
OSCAR_IMAGE_FOLDER = 'images/products'

# Oscar's default product image size
OSCAR_THUMBNAIL_SIZES = {
    'dashboard': '100x100',
    'catalogue': '150x150',
    'product_page': '300x300',
    'checkout': '80x80',
}

# Oscar's default product image quality
OSCAR_THUMBNAIL_QUALITY = 90

# Oscar's default product image format
OSCAR_THUMBNAIL_FORMAT = 'PNG'

# Oscar's default product image background
OSCAR_THUMBNAIL_BG_COLOUR = '#FFFFFF'

# Oscar's default product image crop
OSCAR_THUMBNAIL_CROP = 'center'

# Oscar's default product image upscale
OSCAR_THUMBNAIL_UPSCALE = True

# Oscar's default product image fill
OSCAR_THUMBNAIL_FILL = True

# Oscar's default product image padding
OSCAR_THUMBNAIL_PADDING = True

# Oscar's default product image padding colour
OSCAR_THUMBNAIL_PADDING_COLOUR = '#FFFFFF'

# Oscar's default product image padding border
OSCAR_THUMBNAIL_PADDING_BORDER = True

# Oscar's default product image padding border colour
OSCAR_THUMBNAIL_PADDING_BORDER_COLOUR = '#000000'

# Oscar's default product image padding border width
OSCAR_THUMBNAIL_PADDING_BORDER_WIDTH = 1

# Oscar's default product image padding border radius
OSCAR_THUMBNAIL_PADDING_BORDER_RADIUS = 0

# Oscar's default product image padding border style
OSCAR_THUMBNAIL_PADDING_BORDER_STYLE = 'solid'

# Oscar's default product image padding border opacity
OSCAR_THUMBNAIL_PADDING_BORDER_OPACITY = 1

# Oscar's default product image padding border shadow
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW = False

# Oscar's default product image padding border shadow colour
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_COLOUR = '#000000'

# Oscar's default product image padding border shadow x
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_X = 0

# Oscar's default product image padding border shadow y
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_Y = 0

# Oscar's default product image padding border shadow blur
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_BLUR = 0

# Oscar's default product image padding border shadow spread
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_SPREAD = 0

# Oscar's default product image padding border shadow inset
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_INSET = False

# Oscar's default product image padding border shadow opacity
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_OPACITY = 1

# Oscar's default product image padding border shadow rgba
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_RGBA = (0, 0, 0, 1)

# Oscar's default product image padding border shadow rgb
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_RGB = (0, 0, 0)

# Oscar's default product image padding border shadow hex
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_HEX = '#000000'

# Oscar's default product image padding border shadow hsv
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_HSV = (0, 0, 0)

# Oscar's default product image padding border shadow hsl
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_HSL = (0, 0, 0)

# Oscar's default product image padding border shadow cmyk
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_CMYK = (0, 0, 0, 0)

# Oscar's default product image padding border shadow gray
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_GRAY = 0

# Oscar's default product image padding border shadow alpha
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_ALPHA = 1

# Oscar's default product image padding border shadow css
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_CSS = '0 0 0 0 rgba(0,0,0,1)'

# Oscar's default product image padding border shadow css inset
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_CSS_INSET = 'inset 0 0 0 0 rgba(0,0,0,1)'

# Oscar's default product image padding border shadow css outset
OSCAR_THUMBNAIL_PADDING_BORDER_SHADOW_CSS_OUTSET = '0 0 0 0 rgba(0,0,0,1)'


try:
    from settings_local import *
except ImportError:
    pass
