# Generated by Django 5.2.4 on 2025-08-08 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_line_num_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='hostel',
            field=models.CharField(default='Indece', max_length=128, verbose_name='Hostel/Hall'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='location',
            field=models.CharField(choices=[('campus', 'Campus'), ('tech_junction', 'Tech Junction'), ('ayeduase', 'Ayeduase'), ('kotei', 'Kotei'), ('atonsu', 'Atonsu'), ('deduako', 'Deduako'), ('new_site', 'New Site')], default='campus', max_length=128, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default='0123456789', help_text='Enter a valid 10-digit phone number starting with 0', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 0.', regex='^0\\d{9}$')], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='room_number',
            field=models.CharField(default='001', max_length=10, verbose_name='Room number'),
        ),
    ]
