# Generated by Django 5.2.4 on 2026-07-18 16:38

import rider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='currency',
            field=models.CharField(default='GHS', max_length=12),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=rider.models.default_delivery_fee, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid out')], default='pending', max_length=12),
        ),
    ]
